---
# file: site.yml
- hosts: all
  user: '{{ deploy_user }}'
  become: yes
  become_user: root
  become_method: sudo

  var_files:
    - "vars/common.yml"
    - [ "vars/{{ ansible_os_family }}.yml", "vars/os_defaults.yml" ]

  roles:
    - base

- include: camera.yml
- include: control.yml
